### ISSUE TITLE
PackagesNotFoundError: The following packages are not available from current channels

### ISSUE THREAD

**Issue by sersancar** [tianqitang1/ContigNet#1]
Hi, 

Running the firt step of the installation (onda create --name ContigNet --file requirements.txt), I have encountered the next error:

Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - aiohttp==3.8.1=py39h2bbff1b_0
  - pyqt==5.9.2=py39hd77b12b_6
  - jedi==0.18.1=py39haa95532_1
  - sip==4.19.13=py39hd77b12b_0
  - zlib==1.2.11=h8cc25b3_4
  - terminado==0.13.1=py39haa95532_0
  - numpy-base==1.19.2=py39hbd0edd7_0
  - mkl-service==2.3.0=py39h196d8e1_0
  - pywinpty==2.0.2=py39h5da7b33_0
  - nbconvert==6.1.0=py39haa95532_0
  - jupyter==1.0.0=py39haa95532_7
  - libpng==1.6.37=h2a8f88b_0
  - openssl==1.1.1m=h2bbff1b_0
  - cffi==1.15.0=py39h2bbff1b_1
  - jupyter_core==4.9.1=py39haa95532_0
  - brotlipy==0.7.0=py39h2bbff1b_1003
  - pytorch==1.10.1=py3.9_cuda11.3_cudnn8_0
  - mkl_fft==1.3.0=py39h46781fe_0
  - scikit-learn==0.23.2=py39hf11a4ad_0
  - markupsafe==2.0.1=py39h2bbff1b_0
  - ipykernel==5.3.4=py39h7b7c402_0
  - torchaudio==0.10.1=py39_cu113
  - vs2015_runtime==14.27.29016=h5e58377_2
  - grpcio==1.42.0=py39hc60d5dd_0
  - widgetsnbextension==3.5.1=py39haa95532_0
  - mypy_extensions==0.4.3=py39haa95532_1
  - importlib-metadata==4.8.2=py39haa95532_0
  - matplotlib==3.3.4=py39haa95532_0
  - qt==5.9.7=vc14h73c81de_0
  - libwebp==1.2.0=h2bbff1b_0
  - argon2-cffi==20.1.0=py39h2bbff1b_1
  - jpeg==9d=h2bbff1b_0
  - pyjwt==2.1.0=py39haa95532_0
  - pysocks==1.7.1=py39haa95532_0
  - zstd==1.4.9=h19a0ad4_0
  - multidict==5.1.0=py39h2bbff1b_2
  - cudatoolkit==11.3.1=h59b6b97_2
  - mkl_random==1.0.2=py39h848d8c7_0
  - python_abi==3.9=1_cp39
  - pywin32==302=py39h827c3e9_1
  - vc==14.2=h21ff451_1
  - frozenlist==1.2.0=py39h2bbff1b_0
  - mistune==0.8.4=py39h2bbff1b_1000
  - numpy==1.19.2=py39h729668d_0
  - tornado==6.1=py39h2bbff1b_0
  - pylint==2.7.0=py39haa95532_1
  - intel-openmp==2022.0.0=haa95532_3663
  - certifi==2021.10.8=py39haa95532_2
  - ncbi-genome-download==0.3.1=pyh5e36f6f_0
  - tk==8.6.11=h2bbff1b_0
  - win_inet_pton==1.1.0=py39haa95532_0
  - tensorboard==2.4.1=pyhd8ed1ab_0
  - typed-ast==1.4.3=py39h2bbff1b_1
  - freetype==2.10.4=hd328e21_0
  - libuv==1.40.0=he774522_0
  - winpty==0.4.3=4
  - pytorch-mutex==1.0=cuda
  - wincertstore==0.2=py39haa95532_2
  - blinker==1.4=py39haa95532_0
  - lz4-c==1.9.3=h2bbff1b_1
  - lazy-object-proxy==1.6.0=py39h2bbff1b_0
  - icu==58.2=ha925a31_3
  - sqlite==3.37.2=h2bbff1b_0
  - ca-certificates==2021.10.26=haa95532_4
  - zstandard==0.16.0=pypi_0
  - kiwisolver==1.3.1=py39hd77b12b_0
  - xz==5.2.5=h62dcd97_0
  - wrapt==1.13.3=py39h2bbff1b_2
  - mccabe==0.6.1=py39haa95532_1
  - ncbi-acc-download==0.2.8=pyh5e36f6f_0
  - scipy==1.6.2=py39h14eb087_0
  - torchvision==0.11.2=py39_cu113
  - setuptools==58.0.4=py39haa95532_0
  - notebook==6.4.6=py39haa95532_0
  - cryptography==3.4.8=py39h71e12ea_0
  - python==3.9.7=h6244533_1
  - entrypoints==0.3=py39haa95532_0
  - ete3==3.1.2=pypi_0
  - protobuf==3.19.1=py39hd77b12b_0
  - libtiff==4.2.0=hd0e1b90_0
  - pyrsistent==0.18.0=py39h196d8e1_0
  - pillow==8.4.0=py39hd45dc43_0
  - ipython==7.31.1=py39haa95532_0
  - patsy==0.5.2=py39haa95532_1
  - pip==21.2.4=py39haa95532_0
  - webencodings==0.5.1=py39haa95532_1
  - yarl==1.6.3=py39h2bbff1b_0
  - biopython==1.78=py39hb82d6ee_1
  - pyzmq==22.3.0=py39hd77b12b_2
  - icc_rt==2019.0.0=h0cc432a_1
  - et_xmlfile==1.1.0=py39haa95532_0
  - regex==2021.8.3=py39h2bbff1b_0
  - matplotlib-base==3.3.4=py39h49ac443_0
  - statsmodels==0.12.2=py39h2bbff1b_0
  - libprotobuf==3.19.1=h23ce68f_0
  - astroid==2.5=py39haa95532_1
  - pandas==1.2.2=py39hf11a4ad_0
  - markdown==3.3.4=py39haa95532_0

Current channels:

  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

Thanks in advance...

**Comment by tianqitang1** [comment]
I was recently aware that the requirements.txt does not work on platforms other than Windows. Please install PyTorch, Numpy, Pandas, Scikit-Learn, Matplotlib, ete3, statsmodels, BioPython and TensorBoard manually, I will update the requirements.txt shortly.

**Comment by tianqitang1** [comment]
New instructions added to README.md
